# Generated by Django 5.0.6 on 2024-05-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img_src', models.CharField(max_length=100, null='default_album.png')),
                ('totalsongs', models.IntegerField(default=0)),
                ('totallikes', models.IntegerField(default=0)),
            ],
        ),
    ]
