# Generated by Django 5.0.6 on 2024-05-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='totalsongs',
        ),
        migrations.AddField(
            model_name='album',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
