# Generated by Django 5.0.6 on 2024-05-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
