# Generated by Django 5.0.6 on 2024-05-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0007_alter_users_managers_rename_is_admin_users_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
