# Generated by Django 5.0.6 on 2024-05-22 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_initial'),
        ('music', '0003_alter_music_album_alter_music_artist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='album.album'),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
