# Generated by Django 5.0.6 on 2024-05-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_music_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
