# Generated by Django 5.0.6 on 2024-05-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_music_album_alter_music_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
